python3 pcs_week_alert_report.py 17
python3 pcs_week_alert_report.py 18
python3 pcs_week_alert_report.py 19
python3 pcs_week_alert_report.py 20
python3 pcs_week_alert_report.py 21
python3 pcs_week_alert_report.py 22
python3 pcs_week_alert_report.py 23
python3 pcs_week_alert_report.py 24
python3 pcs_week_alert_report.py 25
python3 pcs_week_alert_report.py 26
python3 pcs_week_alert_report.py 27
python3 pcs_week_alert_report.py 28
python3 pcs_week_alert_report.py 29
python3 pcs_week_alert_report.py 30
python3 pcs_week_alert_report.py 31
python3 pcs_week_alert_report.py 32
python3 pcs_week_alert_report.py 33
python3 pcs_week_alert_report.py 34
python3 pcs_week_alert_report.py 35
python3 pcs_week_alert_report.py 36
python3 pcs_week_alert_report.py 37
python3 pcs_week_alert_report.py 38
python3 pcs_week_alert_report.py 39
python3 pcs_week_alert_report.py 40
python3 pcs_week_alert_report.py 41
python3 pcs_week_alert_report.py 42
python3 pcs_week_alert_report.py 43
python3 pcs_week_alert_report.py 44
python3 pcs_week_alert_report.py 45
python3 pcs_week_alert_report.py 46
python3 pcs_week_alert_report.py 47
python3 pcs_week_alert_report.py 48
python3 pcs_week_alert_report.py 49
python3 pcs_week_alert_report.py 50
